config/routes.rb
Rails.application.routes.draw do
  
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'home', to: 'pages#home'
  get 'signup', to: 'users#new'
  resources :users, expect: [:new]    
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :categories, expect: [:destroy]



end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                     uniqueness: { case_sensitive: false },
                     length: { minimum: 3, maximum: 25 }
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                     uniqueness: { case_sensitive: false },
                     length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
      @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def new
      @user = User.new
    end   

    def index
      @users = User.paginate(page: params[:page], per_page: 5)
    end

    def edit
    end

  
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Welcome to the test app #{@user.username}, you have succesfully signed up." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Your account information was succcesfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy!
    respond_to do |format|
      format.html { redirect_to users_path, notice: "Account and all associated articles are successfully deleted.." }
      format.json { head :no_content }
    end
  end



    private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own account.. "
        redirect_to @user
      end
    end

end 

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
     <%= render 'shared/error', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |form| %>
        <div class="form-group row mb-2">
          <%= form.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
          <%= form.text_field :username, class:"form-control shadow-lg rounded", placeholder: "Enter a username" %>
          </div>
        </div> 

        <div class="form-group row mb-2">
          <%= form.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
          <%= form.email_field :email, class:"form-control shadow-lg rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row mb-2">
          <%= form.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
          <%= form.password_field :password, class:"form-control shadow-lg rounded", placeholder: "Choose a Password" %>
          </div>
        </div>

        <div class="form-group col text-center">
          <%= form.submit(@user.new_record? ? "Sign up" : "Update account", class:"btn btn-outline-light") %>
          <%= link_to "Back Home page", home_path, class: "btn btn-outline-success"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
  <h1 class="text-center mt-2">Edit your profile</h1>
  <%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-2">Test Appers</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-3 bg-white rounded">
        <div class="card-header">
          <%= link_to user.username, user %>
        </div>
        <div class="card-body">
        <h5 class="card-title">
          <%= link_to gravatar_for(user, size: 100), user %>
        </h5>
          <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
          <%= link_to "View Profile", user, class: "btn btn-outline-success" %>
          <% if logged_in? %> 
            <% if user == current_user %>  
              <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>  
            <% end %>
            <% if current_user.admin? %>
              <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger",data: {turbo_method: :delete, confirm: "Are you sure you want to delete this article?"} %> 
              <% end %>       
          <% end %>  
        </div>
        <div class="card-footer text-muted">
          <small>joined <%= time_ago_in_words(user.created_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>
  <% end%>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
  <h1 class="text-center mt-2">Sign up for Test App</h1>
  <%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>  
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>