config/routes.rb
Rails.application.routes.draw do
  
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'home', to: 'pages#home'
  get 'signup', to: 'users#new'
  resources :users, expect: [:new]    
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :categories, expect: [:destroy]



end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :require_admin, except: %i[index show]  

  # GET /categories or /categories.json
  def index
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end

  # GET /categories/1 or /categories/1.json
  def show
    # @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories or /categories.json
  def create
    respond_to do |format|
    @category = Category.new(category_params)
      if @category.save
        format.html { redirect_to @category, notice: "Category name successfully created." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category name successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !(logged_in? && current_user.admin?)
        flash[:alert] = "Only admins can perform that action"
        redirect_to categories_url
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill text-bg-warning mr-2" %>

app/views/categories/_form.html.erb
<%= render 'shared/error', obj: @category %>
  <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |form| %>
    
    <div class="form-group row mb-2">
      <%= form.label :name, "Category name", class: "col-2 col-form-label text-light" %>
      <div class="col-10">
      <%= form.text_field :name, class:"form-control shadow-lg rounded", placeholder: "Enter a name" %>
      </div>
    </div> 

    <div class="form-group col text-center">
      <%= form.submit class:"btn btn-outline-light" %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-2">Edit category name</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3 text-center">
      <%= link_to "Back category", category_path(@category), class: "btn btn-outline-success" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
  <div class="row justify-content-md-center">
    <div class="col-4 mt-4">
      <div class="card text-center shadow mb-3 bg-white rounded">

        <div class="card-body">
          <h5 class="card-title"><%= link_to category.name, category_path(category), class:"text-success" %></h5>
          <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
        </div>

        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(category.created_at) %> ago,
            edited  <%= time_ago_in_words(category.updated_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>
  <% end%>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-2">Create a new category</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3 text-center">
      <%= link_to "Back category listing", categories_path, class: "btn btn-outline-success" %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>  
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>