config/routes.rb
Rails.application.routes.draw do
  
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'home', to: 'pages#home'
  get 'signup', to: 'users#new'
  resources :users, expect: [:new]    
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :categories, expect: [:destroy]



end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to "Shraddha Sheladiya", "https://imjaydip.in", class: "text-white"
      %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "TEST APP", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Users", users_path, class: "nav-link" %>
            </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <% if logged_in? %>
                <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
              <% end %>
                <%= link_to "View article", articles_path, class: "dropdown-item" %>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>

            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <% if logged_in? && current_user.admin? %>
                <%= link_to "Create new Category", new_category_path, class: "dropdown-item" %>
              <% end %>
                <%= link_to "View Categories", categories_path, class: "dropdown-item" %>
            </ul>
          </li>


          <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> [<%= current_user.username %>]</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %> 
                <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", data: {turbo_method: :delete, confirm: "Are you sure you want to delete this article?"} %>
            </ul>
          </li>
            
            <li class="nav-item">
              <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", signup_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search"    aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>  
    <div id="page-content">
      <%= render 'layouts/messages' %>      
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>